Thomas-Tsai/partclone

src/deplib_version.c
When building with gcc5, string.h is no longer implicit included and the
source must declare the includes.
Otherwise, the build 'warns' about this error (which can have quite bad
results):
[   26s] ./src/deplib_version.c:31:9: warning: implicit declaration of
function 'strcmp' [-Wimplicit-function-declaration]
[   26s]      if (strcmp(libfs, "ntfs") == 0){
Spotted by openSUSE Build Root Policy verification:
[   40s] E: partclone implicit-fortify-decl ./src/deplib_version.c:31
=> Fix missing includes

tests/_common, tests/mini_clone_restore_test
Currently, there is no way to customize file size and block size in mini clone test.
This PR fixes above issue by adding support to such parameters.
=> Customize mini clone test fs and bs

src/f2fsclone.c
This commit fixes following the errors which are reported cppcheck.
src/f2fsclone.c:88]: (error) Uninitialized variable: bused
src/f2fsclone.c:98]: (error) Uninitialized variable: bfree
=> f2fs: remove unused variables

src/f2fs/fsck.c
This commit fixes following the error which is reported by cppcheck.
src/f2fs/fsck.c:508]: (error) Common realloc mistake: 'tree_mark' nulled but not freed upon failure
=> f2fs: fix common realloc mistake

src/partclone.c
This commit fixes following the error which is reported by cppcheck:
src/partclone.c:803]: (error) Memory leak: real_fsname
=> partclone: fix memory leak

src/xfsclone.c
xfsclone.c:211:9: warning: comparison between signed and unsigned [-Wsign-compare]
if (i == be32_to_cpu(agf->agf_fllast))
^
xfsclone.c:213:11: warning: comparison between signed and unsigned [-Wsign-compare]
if (++i == XFS_AGFL_SIZE(mp))
=> Fix sign-compare warnings in xfsclone.c

configure.ac
Currently, if AC_ARG_ENABLE contains '--enable-foo' and user passes
'--disable-foo' to './configure', '$enable_foo' will contain 'yes'.
This commit strips 'action-if-(un)specified' arguments of AC_ARG_ENABLE
in order to leverage the default behaviour, which sets `$enable_*'
content appropriately.
This PR is related to https://github.com/Thomas-Tsai/partclone/pull/59, but I hope that my solution is cleaner.
=> fix AC_ARG_ENABLE so that --disable-* options work as expected

tests/_common
In the average Fedora build environment, `locate` does not exist in `$PATH` (aside of that, it would require an `updatedb` before which is IMHO a waste of resources, given the whole filesystem is indexed). Thus use `which` if `locate` does not exist, this is backwards compatible, but serves build environments as well.
=> Use "which" if "locate" doesn't exist (e.g. in build environments)

src/hfsplusclone.c
blocks starts beyond disk sector 1048576. Also see:
https://forums.fogproject.org/topic/10536/macbook-air-capture-fail
=> Prevent from integer overflow that occours if one of the extent

fail-mbr/compile-mbr.sh
By default only `dpkg-architecture` is queried – which poorly fails on RPM-based architectures, such as Fedora or CentOS. The patch additionally adds `$RPM_ARCH` in the same manner like existing `dpkg-architecture` is being used.
=> Honor $RPM_ARCH alternatively to dpkg-architecture(1) for build-time architecture detection

src/btrfs/volumes.c, src/btrfsclone.c, src/main.c
Bugs were minor, but prevent from cloning a btrfs partition:
- bad assertion check;
- missing variable initialization.
These fixes seem sufficient at least in my case.
I don't know how an additional change can be excluded from the pull request: it fails to fix the issue with the progress bar. Though, it fixes a type that seems incorrect in main.c.
=> fix small bugs in btrfs support

tests/_common
The average buildsystem (such as the Fedora one) does not have an interactive shell, thus waiting for interactive input is not a good idea. Simply skip the question on non-interactive shells.
=> Distinguish between (non-)interactive shell (courtesy of "UNIX F.A.Q.", 1993)

docs/partclone.8, src/main.c, src/partclone.c, src/partclone.h, src/readblock.c
The ncurses mode obviously conflicts with writing the cloned image
to stdout. Piping the image to a command to compress it while in
ncurses mode is unusable because of this.
Fix it by adding a new option -x / --compresscmd CMD that is
executed in a write-only pipe internally by partclone.
Signed-off-by: Böszörményi Zoltán <zboszor@pr.hu>
=> Support compressed cloned images

src/Makefile.am, src/main.c
We can create torrent info while converting image to BT format.
`torrent.info` will place at `<target dir>`
Use [partclone_create_torrent.py](https://github.com/tjjh89017/ezio/blob/master/utils/partclone_create_torrent.py) to make "true" torrent.
```
cat torrent.info | ./partclone_create_torrent.py
ls -l a.torrent # the torrent we need
```
https://github.com/tjjh89017/ezio/blob/master/utils/partclone_create_torrent.py#L25
**IMPORTNAT**
L25 `a/` will be the directory name for files
Change it to what you what, otherwise EZIO may not find files to seed.
=> Create Torrent Info while converting image to BT format

src/main.c
fixes compilation with musl libc
Error message
[Full log on travis](https://travis-ci.org/void-linux/void-packages/jobs/447602285)
```
cc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\"/usr/share/locale\" -D_FILE_OFFSET_BITS=64  -DDD -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -DBTRFS_DISABLE_BACKTRACE  -Wall -MT partclone_dd-main.o -MD -MP -MF .deps/partclone_dd-main.Tpo -c -o partclone_dd-main.o `test -f 'main.c' || echo './'`main.c
main.c: In function 'main':
main.c:625:22: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'INT8_MAX'?
char torrent_name[PATH_MAX + 1] = {'\0'};
^~~~~~~~
INT8_MAX
```
=> src/main.c: add limits.h include for PATH_MAX

src/main.c, src/partclone.c
too many malloc and free will cause slow performance
make aligned (to 512) buffer only affect write_buffer and restore mode
=> Performance Fix up

src/Makefile.am, src/main.c, src/partclone.c, src/partclone.h, src/torrent_helper.c, src/torrent_helper.h
1. we can `restore` image to BT format and generate `torrent.info` for `partclone_create_torrent.py` [1] simultaneously
2. we can `clone` disk but no output image for BT deploy read/write from disk directly. We don't need to create partclone image and then convert it to BT format. It will generate `torrent.info` directly for use.
Limited:
There is possible that `restore` and `clone` mode generate different `torrent.info`. But two `torrent.info` will cover the same range of disk, so don't worry about that
[1] This script is under developed. it still needs some fix https://github.com/tjjh89017/ezio/blob/master/utils/partclone_create_torrent.py
=> Generate BT info directly

src/main.c, src/partclone.c
Because we don't use too much disk space.
Torrent is small enough
=> Fixup when torrent_only enable, we don't need to check disk free space

src/partclone.c
"print_version" long option should have been "version" to correctly match what is listed in help
=> fix typo in option to print version

src/main.c
in restore mode (convert partclone image to BT image)
correct the args passed into torrent helper
=> Fixup buffer address passed into torrent helper in restore mode

src/main.c
If opt.ignore_crc is set, must not check the (uncomputed) checksum of
the latest chunk
Although I have not studied the code in details, this seems to fix the problem.
=> Fix for issue #121

src/progress.c
args: -s /dev/nvme0n1p5 -o - -c -z 1048576 -L /var/log/partclone.log
/dev/nvme0n1p5 is the swap partition, I noticed that in the calculate_speed function of progress.c, percent = prog->unit * copied; percent is NaN, prog->unit is Inf, so the next judgment was not successfully modified percent, which caused the retained to be the wrong value, and the strftime function crashed.
=> fix: crash when backing up swap partition

config.h.in, configure.ac, src/torrent_helper.c, src/torrent_helper.h
OpenSSL 3.0 deprecated the direct / individual crypto API variants
so they produce deprecation warnings now. OpenSSL also allows hiding
deprecated APIs so in this configuration partclone can't be built.
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
=> Use EVP OpenSSL API

src/torrent_helper.c, src/torrent_helper.h
torrent_helper.h didn't have #include <config.h> so
the settings didn't actually take effect so the direct SHA1 API
was still in use.
Also fix copy&paste errors that didn't turn up in the build
but after adding #include <config.h> to torrent_helper.h they did.
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
This is a follow up to #165
Sorry for the mess, I only actually tested the build before on a system with  OpenSSL 1.1.1l.
=> Fix using EVP OpenSSL API

docs/partclone.8, docs/partclone.chkimg.8, docs/partclone.chkimg.xml, docs/partclone.dd.8, docs/partclone.dd.xml, docs/partclone.imager.8, docs/partclone.imager.xml, docs/partclone.restore.8, docs/partclone.restore.xml, docs/partclone.xml
Fix issue #170: "normanly" = "in the Norman way" highly unlikely to be intended here, replacing with "normally"
=> Docs typo "normanly"

src/apfsclone.c, src/apfsclone.h
Previously space manager was read from checkpoint data area.
According to Apple File System Reference, finding space manager from
a checkpoint map is needed.
=> fix apfs support

src/main.c, src/partclone.c, src/partclone.h
Previously lseek() was always used for an output device file when
restoring or copying device-to-device.  With this patch, stdout is
supported by writing zeros instead of lseek() only if stdout is
specified as output.
=> stdout support

src/partclone.c
C99 for loop breaks currently building of partclone on RHEL/CentOS 7
=> Change C99 for loop init to C89 for compatibility

config.guess, config.h.in, config.sub, install-sh, po/Makevars.template, test-driver
Generated using "autoreconf -fi" to support new arch.
Current version refuses to build on RISC-V with the following error:
```text
This script, last modified 2014-03-23, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from
http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
```
Updating to the newest fixes the error.
=> update autotools build files

src/main.c, src/partclone.c
Prevent compiler warnings and make it more fail-safe.
=> Avoid redefining _GNU_SOURCE, _LARGEFILE64_SOURCE

src/fuseimg.c
Prior to version 3.0, `fuse_init()` did not have a second argument, nor was `struct fuse_config` defined.
=> Support FUSE 2.x API

src/fuseimg.c
Print a help page on incorrect `partclone.imgfuse` invocation rather than just crash.
=> Check argument count in partclone.imgfuse

src/Makefile.am
Unlike the rest of source code, these modules bring many additional header files and therefore append include paths, but do not account for `VPATH` being different from `pwd`, resulting in failed out-of-tree builds.
PS. I wonder why so much header files are bundled, rather than using system-provided versions. Same question: #129
=> Support out-of-tree builds for BTRFS and XFS

src/btrfs/ctree.c, src/btrfs/extent-tree.c, src/btrfs/volumes.c, src/xfs/libxfs/xfs_sb.c
Make extra-cautious compilers happy.
=> Avoid uninitialized variables to prevent compiler warnings

configure.ac, src/torrent_helper.c, src/torrent_helper.h
OpenSSL prior to 1.1.0 and LibreSSL prior to 2.7.0 come without `EVP_MD_CTX_reset()`.
=> Check for EVP_MD_CTX_reset

src/apfsclone.c
Unlike #194, this patch involves *deleting* some code parts in assumption that they won't be used in foreseeable future. The only exception is explicit type casting which is recommended to adopt even if other corrections are rejected for the sake of future development.
=> Remove unused variables to silence compiler warnings

configure.ac
When just a comma is printed, it looks somewhat misleading for newcomers, especially when all filesystems are in fact disabled.
=> Detect FUSE version and explicitly print “yes” or “no” regarding filesystem support

fail-mbr/Makefile.am, fail-mbr/compile-mbr.sh
This patch:
* enables out-of-tree builds of `fail-mbr`;
* disables x86-specific actions for non-x86 hosts;
* unifies host architecture checks;
* expands artifact removal list by including `objdump` reports as well.
=> Fix MBR builds for x86, non-x86 and out-of-tree

src/xfsclone.c
log message output as follows, so add new line.
```
Initial image hdr - get Super Block from partition
Reading Super Block
xfsclone.c: Open /dev/sda9 successfullyxfsclone.c: source_blocksize 4096 source_sectorsize = 512
xfsclone.c: first_residue 2048 tmp_residue 2048
```
Thank you.
=> fix log message to add new line after "Open devicefile successfully"

docs/partclone.8, docs/partclone.chkimg.8, docs/partclone.chkimg.xml, docs/partclone.dd.8, docs/partclone.fstype.8, docs/partclone.fstype.xml, docs/partclone.imager.8, docs/partclone.imager.xml, docs/partclone.info.8, docs/partclone.info.xml, docs/partclone.restore.8, docs/partclone.restore.xml, docs/partclone.xml
When writing in English (not a programming language or math), the rule is: put a space before the opening parenthesis.
=> Add missing space before opening parenthesis

tests/fat.test
Otherwise `src/fatclone.c` fails on s390x like this:
> get_fat_type, 66, ERROR: data_size count error
> get_fat_type, 70, ERROR: clusters count error
Alternatively, if you need access to an s390x system to add big-endian support to `src/fatclone.c`, please let me know.
=> Skip FAT tests on big-endian architectures

tests/f2fs.test
Otherwise `partclone.f2fs` fails on s390x like this:
> $ partclone.f2fs -d -c -s floppy.raw -O floppy.img -F -L test.log -a 1 -k 17
> Segmentation fault      (core dumped)
Alternatively, if you need access to an s390x system to add big-endian support to `partclone.f2fs`, please let me know.
=> Skip F2FS tests on big-endian architectures

tests/_common
=> Increase XFS default test image size to 300+ MB

fail-mbr/compile-mbr.sh
GNU Binutils 2.36 configures with `--enable-x86-used-note` by default for Linux/x86. This adds the new section `.note.gnu.build-id`, which needs to be removed.
When building `fail-mbr.o` with current binutils, `ld` links the file into an executable format. However this is not accepted by current binutils for building `fail-mbr.image`; thus it requires `-Wl,--relocatable` for the former and `-Wl,--no-dynamic-linker` for the latter.
See also:
- https://sourceware.org/pipermail/binutils/2021-January/115071.html
- https://sourceware.org/bugzilla/show_bug.cgi?id=26223
- https://sourceware.org/bugzilla/show_bug.cgi?id=27753
- https://lists.denx.de/pipermail/u-boot/2021-June/452303.html
Fixes: #159
=> fail-mbr: Remove binutils section .note.gnu.build-id using objcopy

tests/Makefile.am
Don't target Btrfs and exFAT tests twice
=> Don't target Btrfs and exFAT tests twice

.github/workflows/manual-on-host.yml
=> split jobs in github action

config.h.in, configure.ac, src/main.c
=> Handle absence of mtrace.h (e.g. uClibc) gracefully

IMAGE_FORMATS.md
This fixes the description of the item at offset 76 which actually is the number of used blocks based on the bitmap. This mistake in the file format description was brought up in issue #234.
=> correction for item at offset 76

configure.ac, m4/compat.m4, src/Makefile.am
As of writing, the bash-completion configuration is installed in the `$(sysconfdir)/bash_completion.d/` directory, while downstreams, such as Linux distributions, might prefer `/usr/share/bash-completion/completions/` (or even another path). For this, the pkg-config configuration file from bash-completion provides a variable being leveraged here (with fallback to the current directory).
To avoid breaking old Linux distributions with pkg-config < 0.28, some autoconf code for backwards compatibility is added, too.
=> Prefer bash-completion directory from pkg-config

src/deplib_version.c, src/partclone.c
opendir() return DIR* but not handled and never closed.
This source just want to remove and create new directory right?
=> Fix tiny resource leak.

src/deplib_version.c
libvmfs_version() return without int value.
=> Add missing return in libvmfs_version().

src/partclone.c
I forgot to test the case where partclone can be found through PATH and
in that case argv[0] does not contains a slash.
Signed-off-by: Patrick Rouleau pfrouleau@gmail.com
=> Fix get_exec_name(): when partclone in installed, there is no '/' in argv0

src/ntfsclone-ng.c
Include the NTFS Boot Record backup in the cloned image
This one depends on your view. A NTFS file system is 1 block smaller than the partition and a copy of the Boot Record is stored in the last sector of the partition. When we clone a NTFS file system, this extra block is not cloned. However, that block is created/modified by mkfs.ntfs, so it seem logical to include it in the image.
This commit update the code to include the extra block in the clone, by increasing the totalblock count and setting the last bit of the bitmap. This have the following effect: the restored file system have the same checksum than the original one. And if we restore the image on a partition with identical geometry than the original, we do not need to run ntfsfixboot.
=> Include the NTFS Boot Record backup in the cloned image

src/progress.c
Not all compilers are smart enough to evaluate `pow()` function and cast the result to integer at compile time, which leads to unresolved dependencies on _libm_ at link-time. Better use standard `UINTxx_C()` macros for explicitly define long integer constants, and bit-shifting operations as long as powers of 2 are considered.
=> Prevent use of run-time floating point math functions for compile-time integer constants

configure.ac
Not doing this check can result in an implicit declaration error.
=> ntfstime.h uses the time.h, sys/stat.h, sys/time.h headers

tests/Makefile.am
The line to add the test was uncommented a while ago, possibly intentionally, but the surrounding lines to make it conditional were not. Disclaimer: I have not actually tried to run the test.
=> Conditionally run the reiser4 test

configure.ac
`src/f2fs/f2fs_fs.h` uses `bswap_64()`, which is part of `byteswap.h` e.g. on glibc-based systems. The `src/f2fs/f2fs_fs.h` already knows how to handle the existence of `byteswap.h`, once there is a configure header check for it. Otherwise building on s390x fails like this:
```
f2fs/f2fs_fs.h:218:25: error: implicit declaration of function ‘bswap_64’; did you mean ‘bswap_32’? [-Wimplicit-function-declaration]
```
=> Check for `byteswap.h` existence for `src/f2fs/f2fs_fs.h`

src/fatclone.c
Fix FAT12 entry parsing to consume 12 bits at a time, using a nibble buffer between reads.
Fix #268
=> FAT12 entries are 12 bits each, not 16

docs/Makefile.am
On my system, DocBook 4.5 stylesheet path is nowhere “a constant”:
```
$ xmlcatalog /etc/xml/catalog http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
/usr/share/xml/docbook/xsl-stylesheets-1.78.1/manpages/docbook.xsl
```
This patch replaces hardcoded path with a generic URI, which is translated to local path automatically, using offline XML catalog.
I also replaced repeating rules for building man pages with a single pattern rule to avoid duplication and facilitate future documentation additions.
=> Detect DocBook path and generalize doc build rules
